services:
  casdoor-noncefix:
    build:
      context: https://github.com/nvanderdoes/casdoor.git#noncefix-4.4.0
      dockerfile: Dockerfile
      target: STANDARD

    image: casdoor-noncefix:4.4.0